[package]
name = "ul_async_trait"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
rust-version = "1.88"
authors = [ "June Welker <junewelker@gmail.com>"]
description = "An async_trait macro which compiles significantly faster"
repository = "https://github.com/itsjunetime/ul_async_trait"
keywords = [ "async_trait", "async" ]
categories = [ "asynchronous", "rust-patterns" ]

[lib]
proc-macro = true

[dependencies]
syn = { version = "3", features = [ "full", "extra-traits", "visit-mut" ] }
proc-macro2 = "1"
quote = "1"

[dev-dependencies]
macrotest = "1"
async-trait = "0.1"
