[package]
name = "ul_async_trait"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
rust-version = "1.88"

[lib]
proc-macro = true

[dependencies]
syn = { version = "3", features = [ "full", "extra-traits", "visit-mut" ] }
proc-macro2 = "1"
quote = "1"
rustc-hash = "2"

[dev-dependencies]
macrotest = "1"
async-trait = "0.1"
